
export default [
  {
    text: 'Date',
    value: 'date',
    show: true,
    sort: null,
    sortQuery: 'created_at',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Time',
    value: 'time',
    show: true,
    sort: null,
    sortQuery: 'created_at',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Bridged At',
    value: 'bridgedAt',
    show: false,
    sort: null,
    sortQuery: 'bridged_at',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Queue Bridged At',
    value: 'queueBridgedAt',
    show: false,
    sort: null,
    sortQuery: 'queue_bridged_at',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Answered At',
    value: 'answeredAt',
    show: false,
    sort: null,
    sortQuery: 'answered_at',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Joined At',
    value: 'joinedAt',
    show: false,
    sort: null,
    sortQuery: 'joined_at',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Leaving At',
    value: 'leavingAt',
    show: false,
    sort: null,
    sortQuery: 'leaving_at',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Hangup At',
    value: 'hangupAt',
    show: false,
    sort: null,
    sortQuery: 'hangup_at',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Reporting At',
    value: 'reportingAt',
    show: false,
    sort: null,
    sortQuery: 'reporting_at',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Direction',
    value: 'direction',
    show: true,
    sort: null,
    sortQuery: 'direction',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'User',
    value: 'user',
    show: true,
    sort: null,
    sortQuery: 'user',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Extension',
    value: 'extension',
    show: false,
    sort: null,
    sortQuery: 'extension',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Destination',
    value: 'destination',
    show: true,
    sort: null,
    sortQuery: 'destination',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'From',
    value: 'from',
    show: true,
    sort: null,
    sortQuery: 'from',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'To',
    value: 'to',
    show: false,
    sort: null,
    sortQuery: 'to',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Gateway',
    value: 'gateway',
    show: true,
    sort: null,
    sortQuery: 'gateway',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Agent',
    value: 'agent',
    show: true,
    sort: null,
    sortQuery: 'agent',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Team',
    value: 'team',
    show: true,
    sort: null,
    sortQuery: 'team',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Queue',
    value: 'queue',
    show: true,
    sort: null,
    sortQuery: 'queue',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Member',
    value: 'member',
    show: true,
    sort: null,
    sortQuery: 'member',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Hangup By',
    value: 'hangupBy',
    show: false,
    sort: null,
    sortQuery: 'hangup_by',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Duration',
    value: 'duration',
    show: true,
    sort: null,
    sortQuery: 'duration',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Queue Duration',
    value: 'queueDuration',
    show: true,
    sort: null,
    sortQuery: 'queue_duration_sec',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Tags',
    value: 'tags',
    show: false,
    sort: null,
    sortQuery: 'tags',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Display',
    value: 'display',
    show: false,
    sort: null,
    sortQuery: 'display',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Hold',
    value: 'hold',
    show: false,
    sort: null,
    sortQuery: 'hold_sec',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Wait',
    value: 'wait',
    show: false,
    sort: null,
    sortQuery: 'wait_sec',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Billing',
    value: 'bill',
    show: false,
    sort: null,
    sortQuery: 'bill_sec',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Reporting',
    value: 'reporting',
    show: false,
    sort: null,
    sortQuery: 'reporting_sec',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Queue Wait',
    value: 'queueWait',
    show: false,
    sort: null,
    sortQuery: 'queue_wait_sec',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Result',
    value: 'result',
    show: false,
    sort: null,
    sortQuery: 'result',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'SIP Code',
    value: 'sipCode',
    show: false,
    sort: null,
    sortQuery: 'sip_code',
    width: 'minmax(120px, 1fr)',
  },
  {
    text: 'Hangup cause',
    value: 'cause',
    show: false,
    sort: null,
    sortQuery: 'cause',
    width: 'minmax(120px, 1fr)',
  },
];
