import { FilterOption } from '@webitel/ui-datalist/filters';

export const filtersOptions: FilterOption[] = [
  FilterOption.Agent,
  FilterOption.AmdResult,
  FilterOption.Contact,
  FilterOption.CreatedAtFrom,
  FilterOption.CreatedAtTo,
  FilterOption.Direction,
  FilterOption.Rated,
  FilterOption.Gateway,
  FilterOption.Grantee,
  FilterOption.Cause,
  FilterOption.Queue,
  FilterOption.RatedBy,
  FilterOption.HasFile,
  FilterOption.Score,
  FilterOption.Tag,
  FilterOption.TalkDuration,
  FilterOption.Team,
  FilterOption.TotalDuration,
  FilterOption.HasTranscription,
  FilterOption.User,
  FilterOption.Variable,
];
