export default [
  {
    value: 'date',
    show: true,
    sort: null,
    field: 'created_at',
  },
  {
    value: 'time',
    show: true,
    sort: null,
    field: 'created_at',
  },
  {
    value: 'direction',
    show: true,
    sort: null,
    field: 'direction',
  },
  {
    value: 'answeredAt',
    show: false,
    sort: null,
    field: 'answered_at',
  },
  {
    value: 'bridgedAt',
    show: false,
    sort: null,
    field: 'bridged_at',
  },
  {
    value: 'queueBridgedAt',
    show: false,
    sort: null,
    field: 'queue_bridged_at',
  },
  {
    value: 'joinedAt',
    show: false,
    sort: null,
    field: 'joined_at',
  },
  {
    value: 'leavingAt',
    show: false,
    sort: null,
    field: 'leaving_at',
  },
  {
    value: 'hangupAt',
    show: false,
    sort: null,
    field: 'hangup_at',
  },
  {
    value: 'reportingAt',
    show: false,
    sort: null,
    field: 'reporting_at',
  },
  {
    value: 'user',
    show: true,
    sort: null,
    field: 'user',
  },
  {
    value: 'extension',
    show: false,
    sort: null,
    field: 'extension',
  },
  {
    value: 'from',
    show: true,
    sort: null,
    field: 'from',
  },
  {
    value: 'to',
    show: true,
    sort: null,
    field: 'to',
  },
  {
    value: 'destination',
    show: true,
    sort: null,
    field: 'destination',
  },
  {
    value: 'gateway',
    show: false,
    sort: null,
    field: 'gateway',
  },
  {
    value: 'agent',
    show: false,
    sort: null,
    field: 'agent',
  },
  {
    value: 'team',
    show: false,
    sort: null,
    field: 'team',
  },
  {
    value: 'queue',
    show: false,
    sort: null,
    field: 'queue',
  },
  {
    value: 'member',
    show: false,
    sort: null,
    field: 'member',
  },
  {
    value: 'hangupBy',
    show: false,
    sort: null,
    field: 'hangup_by',
  },
  {
    value: 'duration',
    show: true,
    sort: null,
    field: 'duration',
  },
  {
    value: 'tags',
    show: false,
    sort: null,
    field: 'tags',
  },
  {
    value: 'display',
    show: false,
    sort: null,
    field: 'display',
  },
  {
    value: 'holdSec',
    show: false,
    sort: null,
    field: 'hold_sec',
  },
  {
    value: 'waitSec',
    show: false,
    sort: null,
    field: 'wait_sec',
  },
  {
    value: 'billSec',
    show: true,
    sort: null,
    field: 'bill_sec',
  },
  {
    value: 'reportingSec',
    show: false,
    sort: null,
    field: 'reporting_sec',
  },
  {
    value: 'queueWaitSec',
    show: false,
    sort: null,
    field: 'queue_wait_sec',
  },
  {
    value: 'queueDurationSec',
    show: false,
    sort: null,
    field: 'queue_duration_sec',
  },
  {
    value: 'result',
    show: false,
    sort: null,
    field: 'result',
  },
  {
    value: 'sipCode',
    show: false,
    sort: null,
    field: 'sip_code',
  },
  {
    value: 'cause',
    show: true,
    sort: null,
    field: 'cause',
  },
  {
    value: 'hangupDisposition',
    show: false,
    sort: null,
    field: 'hangup_disposition',
  },
  {
    value: 'amdResult',
    show: false,
    sort: null,
    field: 'amd_result',
  },
  {
    value: 'agentDescription',
    show: false,
    sort: null,
    field: 'agent_description',
  },
];
