import { WtTableHeader } from '@webitel/ui-sdk/src/components/wt-table/types/WtTable.type.js';

export const headers: WtTableHeader[] = [
  {
    value: 'date',
    show: true,
    sort: null,
    field: 'created_at',
  },
  {
    value: 'time',
    show: true,
    sort: null,
    field: 'created_at',
  },
  {
    value: 'direction',
    show: true,
    sort: null,
    field: 'direction',
  },
  {
    value: 'answeredAt',
    show: false,
    sort: null,
    field: 'answered_at',
  },
  {
    value: 'bridgedAt',
    show: false,
    sort: null,
    field: 'bridged_at',
  },
  {
    value: 'queueBridgedAt',
    show: false,
    sort: null,
    field: 'queue_bridged_at',
  },
  {
    value: 'joinedAt',
    show: false,
    sort: null,
    field: 'joined_at',
  },
  {
    value: 'leavingAt',
    show: false,
    sort: null,
    field: 'leaving_at',
  },
  {
    value: 'hangupAt',
    show: false,
    sort: null,
    field: 'hangup_at',
  },
  {
    value: 'hangupPhrase',
    show: true,
    sort: null,
    field: 'hangup_phrase',
  },
  {
    value: 'reportingAt',
    show: false,
    sort: null,
    field: 'reporting_at',
  },
  {
    value: 'user',
    show: true,
    sort: null,
    field: 'user',
  },
  {
    value: 'extension',
    show: false,
    sort: null,
    field: 'extension',
  },
  {
    value: 'from',
    show: true,
    field: 'from',
  },
  {
    value: 'to',
    show: true,
    field: 'to',
  },
  {
    value: 'destination',
    show: true,
    sort: null,
    field: 'destination',
  },
  {
    value: 'gateway',
    show: false,
    sort: null,
    field: 'gateway',
  },
  {
    value: 'agent',
    show: false,
    sort: null,
    field: 'agent',
  },
  {
    value: 'team',
    show: false,
    sort: null,
    field: 'team',
  },
  {
    value: 'queue',
    show: false,
    sort: null,
    field: 'queue',
  },
  {
    value: 'member',
    show: false,
    sort: null,
    field: 'member',
  },
  {
    value: 'hangupBy',
    show: false,
    sort: null,
    field: 'hangup_by',
  },
  {
    value: 'duration',
    show: true,
    sort: null,
    field: 'duration',
  },
  {
    value: 'screencast',
    show: false,
    sort: undefined,
    field: 'screencast',
    locale: 'vocabulary.screencast',
  },
  {
    value: 'tags',
    show: false,
    sort: null,
    field: 'tags',
  },
  {
    value: 'display',
    show: false,
    sort: null,
    field: 'display',
  },
  {
    value: 'holdSec',
    show: false,
    sort: null,
    field: 'hold_sec',
  },
  {
    value: 'waitSec',
    show: false,
    sort: null,
    field: 'wait_sec',
  },
  {
    value: 'billSec',
    show: true,
    sort: null,
    field: 'bill_sec',
  },
  {
    value: 'talkSec',
    show: true,
    sort: null,
    field: 'talk_sec',
  },
  {
    value: 'reportingSec',
    show: false,
    sort: null,
    field: 'reporting_sec',
  },
  {
    value: 'queueWaitSec',
    show: false,
    sort: null,
    field: 'queue_wait_sec',
  },
  {
    value: 'queueDurationSec',
    show: false,
    sort: null,
    field: 'queue_duration_sec',
  },
  {
    value: 'result',
    show: false,
    sort: null,
    field: 'result',
  },
  {
    value: 'sipCode',
    show: false,
    sort: null,
    field: 'sip_code',
  },
  {
    value: 'cause',
    show: true,
    sort: null,
    field: 'cause',
  },
  {
    value: 'hangupDisposition',
    show: false,
    sort: null,
    field: 'hangup_disposition',
  },
  {
    value: 'amdResult',
    show: false,
    sort: null,
    field: 'amd_result',
  },
  {
    value: 'agentDescription',
    show: false,
    sort: null,
    field: 'agent_description',
  },
  {
    value: 'blindTransfer',
    show: false,
    sort: null,
    field: 'blind_transfer',
  },
  {
    value: 'grantee',
    show: false,
    sort: null,
    field: 'grantee',
  },
  {
    value: 'score',
    show: false,
    sort: null,
    field: 'score_required',
  },
  {
    value: 'ratedBy',
    show: false,
    sort: null,
    field: 'rated_by',
  },
  {
    value: 'memberId',
    show: false,
    sort: null,
    field: 'member',
  },
  {
    value: 'attemptId',
    show: false,
    sort: null,
    field: 'attempt_id',
  },
  {
    value: 'contact',
    show: false,
    sort: null,
    field: 'contact',
  },
].map((header) => ({
  locale: `fields.${header.value}`,
  ...header,
}));
